
package test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.8.91 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IpmsWebApi", targetNamespace = "http://192.168.1.201:9999/IpmsWebApi.wsdl", wsdlLocation = "http://192.168.1.201:9999/IpmsWebApiServer.cgi")
public class IpmsWebApi
    extends Service
{

    private final static URL IPMSWEBAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.IpmsWebApi.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = test.IpmsWebApi.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.1.201:9999/IpmsWebApiServer.cgi");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.201:9999/IpmsWebApiServer.cgi', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IPMSWEBAPI_WSDL_LOCATION = url;
    }

    public IpmsWebApi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IpmsWebApi() {
        super(IPMSWEBAPI_WSDL_LOCATION, new QName("http://192.168.1.201:9999/IpmsWebApi.wsdl", "IpmsWebApi"));
    }

    /**
     * 
     * @return
     *     returns IpmsWebApiPortType
     */
    @WebEndpoint(name = "IpmsWebApi")
    public IpmsWebApiPortType getIpmsWebApi() {
        return super.getPort(new QName("http://192.168.1.201:9999/IpmsWebApi.wsdl", "IpmsWebApi"), IpmsWebApiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IpmsWebApiPortType
     */
    @WebEndpoint(name = "IpmsWebApi")
    public IpmsWebApiPortType getIpmsWebApi(WebServiceFeature... features) {
        return super.getPort(new QName("http://192.168.1.201:9999/IpmsWebApi.wsdl", "IpmsWebApi"), IpmsWebApiPortType.class, features);
    }

}
