
package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IpmsWebApiPortType", targetNamespace = "http://192.168.1.201:9999/IpmsWebApi.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IpmsWebApiPortType {


    /**
     * Service definition of function ns__GetWorkOrderSystemAccount
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWorkOrderSystemAccount")
    @WebResult(name = "result", partName = "result")
    public String getWorkOrderSystemAccount();

    /**
     * Service definition of function ns__IpmsWorkOrderSignIn
     * 
     * @param pwd
     * @param usr
     * @return
     *     returns int
     */
    @WebMethod(operationName = "IpmsWorkOrderSignIn")
    @WebResult(name = "result", partName = "result")
    public int ipmsWorkOrderSignIn(
        @WebParam(name = "usr", partName = "usr")
        String usr,
        @WebParam(name = "pwd", partName = "pwd")
        String pwd);

}
